# .github/workflows/pytest.yml
name: Programming Assignment 1 Pytest

on:
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      if [ -f requirements-test.txt ]: then pip install -r requirements-test.txt; fi

    - name: Run tests
      run: |
        pytest
